apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "firebreak.fullname" . }}-output-pvc
  labels:
    {{- include "firebreak.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.output.storage | default "5Gi" }}
