apiVersion: v1
kind: Service
metadata:
  name: {{ include "firebreak.fullname" . }}-orchestrator
  labels:
    {{- include "firebreak.labels" . | nindent 4 }}
    app: orchestrator
spec:
  type: ClusterIP
  selector:
    {{- include "firebreak.selectorLabels" . | nindent 4 }}
    app: orchestrator
  ports:
    - name: http
      port: 5000
      targetPort: http
    - name: metrics
      port: 5001
      targetPort: metrics
